// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX71SMkQZs9qHAkb-reSgARhDFWx-TAjI',
    appId: '1:763760280606:web:6d4249d4c3b27da26e5a0f',
    messagingSenderId: '763760280606',
    projectId: 'ethioshop-2253',
    authDomain: 'ethioshop-2253.firebaseapp.com',
    storageBucket: 'ethioshop-2253.firebasestorage.app',
    measurementId: 'G-ZYBER6S1Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGSK59SdpDF_1UoyfHMnCAAZjPA2H7R44',
    appId: '1:763760280606:android:110148aec8d5f99c6e5a0f',
    messagingSenderId: '763760280606',
    projectId: 'ethioshop-2253',
    storageBucket: 'ethioshop-2253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX71SMkQZs9qHAkb-reSgARhDFWx-TAjI',
    appId: '1:763760280606:ios:110148aec8d5f99c6e5a0f',
    messagingSenderId: '763760280606',
    projectId: 'ethioshop-2253',
    storageBucket: 'ethioshop-2253.firebasestorage.app',
    iosClientId:
        '763760280606-ios.apps.googleusercontent.com',
    iosBundleId: 'com.ethio.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX71SMkQZs9qHAkb-reSgARhDFWx-TAjI',
    appId: '1:763760280606:ios:110148aec8d5f99c6e5a0f',
    messagingSenderId: '763760280606',
    projectId: 'ethioshop-2253',
    storageBucket: 'ethioshop-2253.firebasestorage.app',
    iosClientId:
        '763760280606-ios.apps.googleusercontent.com',
    iosBundleId: 'com.ethio.shop',
  );
}
